name: Pull Request Handler

on:
  pull_request:
    types: [opened]

jobs:
  run-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello! A new Pull Request has been opened."

      - name: run python
        run: python hello_world.py
